### PR TITLE
Read me Update

### PR DESCRIPTION
**Pull request by mayankkumar2**

### CODE REVIEW

**Comment by Geek-ubaid** [comment]
The readme is not updated completely.
Add the following things in the readme:
1. Add a descriptive description in the readme
2. Add the prerequisites
3. Add contributors section.

**Comment by searchformyusername** [comment]
@mayankkumar2 
Don't push frequent updates of the same thing

image

and make meaningful commits.
Use [this](https://dillinger.io/) to see live changes on markdown files (.md)

**Comment by L04DB4L4NC3R** [comment]
@mayankkumar2 when can we expect the changes?

**Comment by mayankkumar2** [comment]
@L04DB4L4NC3R I will make the changes by the end of the day

**Comment by L04DB4L4NC3R** [comment]
Why did you close the PR? Update in this only

**Comment by mayankkumar2** [comment]
@L04DB4L4NC3R I already made another pull request that was merged.

**Pull request closed without merging**
